_target_: src.architectures.huggingface_architecture.HuggingFaceArchitecture

model:
  _target_: src.architectures.models.huggingface_model.HuggingFaceModel
  pretrained_model_name: ${pretrained_model_name}
  num_labels: ${num_labels}

num_labels: ${num_labels}
average: macro
strategy: ${strategy}
lr: ${lr}
period: ${period}
eta_min: ${eta_min}
interval: step
