_target_: src.datasets.huggingface_dataset.KaggleLeashBELKADataset
data_path: ${connected_dir}/data
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
data_column_name: ${data_column_name}
target_column_names: ${target_column_names}
num_devices: ${devices}
batch_size: ${batch_size}
pretrained_model_name: ${pretrained_model_name}
data_max_length: ${data_max_length}
