defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: kaggle-leash-BELKA
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

submission_file: ${connected_dir}/data/sample_submission.csv
result_column_name: binds
voted_file: ${connected_dir}/submissions/${voted_name}.csv

votings:
  prob1: 0.5
  prob2: 0.5
